# Generated by Django 3.0.5 on 2020-11-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201029_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='description',
            field=models.TextField(default='Your first map!', max_length=5000),
        ),
    ]
